// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABr3vp3YaIJiAvj_SNoTNe6_hb0Siou-w',
    appId: '1:305251651255:web:1ec25e245ee9867dbdc732',
    messagingSenderId: '305251651255',
    projectId: 'counter-app-95ac2',
    authDomain: 'counter-app-95ac2.firebaseapp.com',
    storageBucket: 'counter-app-95ac2.firebasestorage.app',
    measurementId: 'G-7LT8K22ZBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALTzYjGjYYarwHhE5r-X_ZC1lcP04GnRw',
    appId: '1:305251651255:android:49fcb51892d3e20fbdc732',
    messagingSenderId: '305251651255',
    projectId: 'counter-app-95ac2',
    storageBucket: 'counter-app-95ac2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ6gY6iPH50dOUzZcyyyyt287CbezhAus',
    appId: '1:305251651255:ios:38201806e6076e3dbdc732',
    messagingSenderId: '305251651255',
    projectId: 'counter-app-95ac2',
    storageBucket: 'counter-app-95ac2.firebasestorage.app',
    iosBundleId: 'com.msa.counter',
  );
}
